<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
    /**
     * @param array $options
     * @return mixed
     */
    public function getCount($options = [])
    {
        $qb = $this->createQueryBuilder('transaction')
            ->select('count(transaction) as total');
        if (array_key_exists('text', $options)) {
            $qb->andWhere('transaction.description LIKE :text')
                ->setParameter('text', '\'%'.$options['text'].'\'');
        }
        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }

    /**
     * @param array $options
     * @return array
     */
    public function getAll($options = [])
    {
        $qb = $this->createQueryBuilder('matter')
            ->select('matter');
        if (array_key_exists('text', $options)) {
            $qb->andWhere('transaction.description LIKE :text')
                ->setParameter('text', '\'%'.$options['text'].'\'');
        }
        $qb->setFirstResult($options['offset'])
            ->setMaxResults($options['limit']);
        $query = $qb->getQuery();

        return $query->getResult();
    }
}
